dist: xenial
language: ruby

cache:
  directories:
    - vendor/bundle
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10
    - node_modules
    - $HOME/.nvm

services:
  - memcached
  - redis-server
  - mysql
  - rabbitmq-server

addons:
  chrome: stable
  postgresql: "10"
  apt:
    sources:
      - sourceline: "ppa:jonathonf/ffmpeg-3"
      - sourceline: "ppa:ubuntuhandbook1/apps"
    packages:
      - ffmpeg
      - mupdf
      - mupdf-tools
      - poppler-utils
      - rabbitmq-server

bundler_args: --jobs 3 --retry 3
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler"

script: './ci.rb'

rvm:
  - 2.6.0
