language: ruby
sudo: false

cache:
  directories:
    - vendor/bundle
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10
    - node_modules
    - $HOME/.nvm

services:
  - memcached
  - redis-server

addons:
  postgresql: 10
  chrome: stable
  apt:
    sources:
      - sourceline: "ppa:mc3man/trusty-media"
      - sourceline: "ppa:ubuntuhandbook1/apps"
      - mysql-5.7-trusty
    packages:
      - ffmpeg
      - mupdf
      - mupdf-tools
      - poppler-utils
      - mysql-server
      - mysql-client
      - postgresql-10
      - postgresql-client-10

bundler_args: --jobs 3 --retry 3
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler"

script: 'ci.rb'

rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head
