language: ruby
sudo: false
dist: xenial

cache:
  directories:
    - vendor/bundle
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10
    - node_modules
    - $HOME/.nvm

services:
  - memcached
  - redis-server
  - mysql
  - postgresql

addons:
  postgresql: 10
  chrome: stable
  apt:
    sources:
      - sourceline: "ppa:mc3man/trusty-media"
      - sourceline: "ppa:ubuntuhandbook1/apps"
    packages:
      - ffmpeg
      - mupdf
      - mupdf-tools
      - poppler-utils

bundler_args: --jobs 3 --retry 3
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system"
  # - "travis_retry gem install bundler"

rvm:
  - 2.5.1

env:
  global:
    - "POSTGRES=10"

matrix:
  include:
    - rvm: 2.5.1
      env:
        - "POSTGRES=9.2"
      addons:
        postgresql: "9.2"
      packages:
        - postgresql-9.2
        - postgresql-client-9.2
      before_install:
        - "sudo service postgresql stop"
        - "sudo service postgresql start 9.2"

script: './ci.rb'
